select YRB_CUSTOMER.NAME, MAXQTY
from YRB_CUSTOMER, (select YRB_CUSTOMER.CID as CUSTCID, max(QNTY) as MAXQTY
from YRB_PURCHASE, YRB_CUSTOMER
where YRB_PURCHASE.CID = YRB_CUSTOMER.CID
group by YRB_CUSTOMER.CID)
where YRB_CUSTOMER.CID = CUSTCID;